os: osx
osx_image: xcode11.3
language: swift

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  jobs:
    - destination='platform=iOS Simulator,OS=13.3,name=iPhone 11' scheme='BlueSteel'
    - destination='platform=iOS Simulator,OS=12.4,name=iPhone 8' scheme='BlueSteel'
    - destination='platform=iOS Simulator,OS=11.4,name=iPhone 7' scheme='BlueSteel'
    - destination='platform=macOS' scheme='BlueSteel'

script:
  #- cp ./id_rsa.pub ~/.ssh/
  - xcodebuild clean test -destination "$destination" -scheme "$scheme" -disableAutomaticPackageResolution | xcpretty  -c; exit ${PIPESTATUS[0]}

stages:
  - Swift
  - Test
  # - Linux

jobs:
  include:
    - stage: Swift
      script: swift test
      name: "macOS Swift"
    # - stage: Linux
    #   os: linux
    #   dist: bionic
    #   language: c
    #   env: SWIFT_BRANCH=swift-5.1.3-release SWIFT_VERSION=swift-5.1.3-RELEASE
    #   install:
    #     - sudo apt-get install clang libicu-dev
    #     - mkdir swift
    #     - curl https://swift.org/builds/$SWIFT_BRANCH/ubuntu1804/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu18.04.tar.gz -s | tar xz -C swift &> /dev/null
    #     - export PATH="$(pwd)/swift/$SWIFT_VERSION-ubuntu18.04/usr/bin:$PATH"
    #   script:
    #     - set -o pipefail
    #     - swift --version
    #     - swift package update
    #     - swift test
    #   name: "Linux"

