language: objective-c
xcode_workspace: BlueSteel.xcworkspace
osx_image: xcode8

git:
  depth: 1
  submodules: false

before_install:
  - git submodule update --init

install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - ( set -o pipefail && xcodebuild -workspace BlueSteel.xcworkspace -configuration Release ONLY_ACTIVE_ARCH=YES -scheme BlueSteel-iOS -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 6s Plus' -destination-timeout 300 clean build 2>&1 | tee "BlueSteel-iOS-build.log" | xcpretty ) && rm "BlueSteel-iOS-build.log"
  - ( set -o pipefail && xcodebuild -workspace BlueSteel.xcworkspace -configuration Release ONLY_ACTIVE_ARCH=YES -scheme BlueSteel-iOS -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 6s Plus' -destination-timeout 300 test 2>&1 | tee "BlueSteel-iOS-test.log" | xcpretty ) && rm "BlueSteel-iOS-test.log"
  - ( set -o pipefail && xcodebuild -workspace BlueSteel.xcworkspace -configuration Release ONLY_ACTIVE_ARCH=YES -scheme BlueSteel-OSX -destination 'platform=macOS' -destination-timeout 300 clean build 2>&1 | tee "BlueSteel-macOS-build.log" | xcpretty ) && rm "BlueSteel-macOS-build.log"
  - ( set -o pipefail && xcodebuild -workspace BlueSteel.xcworkspace -configuration Release ONLY_ACTIVE_ARCH=YES -scheme BlueSteel-OSX -destination 'platform=macOS' -destination-timeout 300 test 2>&1 | tee "BlueSteel-macOS-test.log" | xcpretty ) && rm "BlueSteel-macOS-test.log"
  - ( set -o pipefail && xcodebuild -workspace BlueSteel.xcworkspace -configuration Release ONLY_ACTIVE_ARCH=YES -scheme BlueSteel-tvOS -destination 'platform=tvOS Simulator,OS=10.0,name=Apple TV 1080p' -destination-timeout 300 clean build 2>&1 | tee "BlueSteel-tvOS-build.log" | xcpretty ) && rm "BlueSteel-tvOS-build.log"
  - ( set -o pipefail && xcodebuild -workspace BlueSteel.xcworkspace -configuration Release ONLY_ACTIVE_ARCH=YES -scheme BlueSteel-tvOS -destination 'platform=tvOS Simulator,OS=10.0,name=Apple TV 1080p' -destination-timeout 300 test 2>&1 | tee "BlueSteel-tvOS-test.log" | xcpretty ) && rm "BlueSteel-tvOS-test.log"
  - ( set -o pipefail && xcodebuild -workspace BlueSteel.xcworkspace -configuration Release ONLY_ACTIVE_ARCH=YES -scheme BlueSteel-watchOS -destination 'platform=watchOS Simulator,OS=3.0,name=Apple Watch - 42mm' -destination-timeout 300 clean build 2>&1 | tee "BlueSteel-watchOS-build.log" | xcpretty ) && rm "BlueSteel-watchOS-build.log"

after_failure:
  - test -f "BlueSteel-iOS-build.log" && tail -n 2500 "BlueSteel-iOS-build.log"
  - test -f "BlueSteel-iOS-test.log" && tail -n 2500 "BlueSteel-iOS-test.log"
  - test -f "BlueSteel-iOS-test.log" && LINE_BEFORE=`cat "BlueSteel-iOS-test.log" | grep -n "IDETestOperationsObserverDebug. Writing diagnostic log for test session to." | awk -F':' '{print $1}'` && LINE=`expr $LINE_BEFORE + 1` && LOG_FILE=`head -n $LINE "BlueSteel-iOS-test.log" | tail -n 1` && cat "$LOG_FILE"
  - test -f "BlueSteel-macOS-build.log" && tail -n 2500 "BlueSteel-macOS-build.log"
  - test -f "BlueSteel-macOS-test.log" && tail -n 2500 "BlueSteel-macOS-test.log"
  - test -f "BlueSteel-macOS-test.log" && LINE_BEFORE=`cat "BlueSteel-macOS-test.log" | grep -n "IDETestOperationsObserverDebug. Writing diagnostic log for test session to." | awk -F':' '{print $1}'` && LINE=`expr $LINE_BEFORE + 1` && LOG_FILE=`head -n $LINE "BlueSteel-macOS-test.log" | tail -n 1` && cat "$LOG_FILE"
  - test -f "BlueSteel-tvOS-build.log" && tail -n 2500 "BlueSteel-tvOS-build.log"
  - test -f "BlueSteel-tvOS-test.log" && tail -n 2500 "BlueSteel-tvOS-test.log"
  - test -f "BlueSteel-tvOS-test.log" && LINE_BEFORE=`cat "BlueSteel-tvOS-test.log" | grep -n "IDETestOperationsObserverDebug. Writing diagnostic log for test session to." | awk -F':' '{print $1}'` && LINE=`expr $LINE_BEFORE + 1` && LOG_FILE=`head -n $LINE "BlueSteel-tvOS-test.log" | tail -n 1` && cat "$LOG_FILE"
  - test -f "BlueSteel-watchOS-build.log" && tail -n 2500 "BlueSteel-watchOS-build.log"

