language: objective-c
xcode_workspace: BlueSteel.xcworkspace
osx_image: xcode8

git:
  depth: 1
  submodules: false

before_install:
  - git submodule update --init

install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - ./BuildControl/bin/travisBuildHelper.sh build iOS
  - ./BuildControl/bin/travisBuildHelper.sh test iOS
  - ./BuildControl/bin/travisBuildHelper.sh build OSX
  - ./BuildControl/bin/travisBuildHelper.sh test OSX
  - ./BuildControl/bin/travisBuildHelper.sh build tvOS
  - ./BuildControl/bin/travisBuildHelper.sh test tvOS
  - ./BuildControl/bin/travisBuildHelper.sh build watchOS

after_failure:
  - test -f "BlueSteel-iOS-build.log" && tail -n 2500 "BlueSteel-iOS-build.log"
  - test -f "BlueSteel-iOS-test.log" && tail -n 2500 "BlueSteel-iOS-test.log"
  - test -f "BlueSteel-iOS-test.log" && LINE_BEFORE=`cat "BlueSteel-iOS-test.log" | grep -n "IDETestOperationsObserverDebug. Writing diagnostic log for test session to." | awk -F':' '{print $1}'` && LINE=`expr $LINE_BEFORE + 1` && LOG_FILE=`head -n $LINE "BlueSteel-iOS-test.log" | tail -n 1` && cat "$LOG_FILE"
  - test -f "BlueSteel-OSX-build.log" && tail -n 2500 "BlueSteel-OSX-build.log"
  - test -f "BlueSteel-OSX-test.log" && tail -n 2500 "BlueSteel-OSX-test.log"
  - test -f "BlueSteel-OSX-test.log" && LINE_BEFORE=`cat "BlueSteel-OSX-test.log" | grep -n "IDETestOperationsObserverDebug. Writing diagnostic log for test session to." | awk -F':' '{print $1}'` && LINE=`expr $LINE_BEFORE + 1` && LOG_FILE=`head -n $LINE "BlueSteel-OSX-test.log" | tail -n 1` && cat "$LOG_FILE"
  - test -f "BlueSteel-tvOS-build.log" && tail -n 2500 "BlueSteel-tvOS-build.log"
  - test -f "BlueSteel-tvOS-test.log" && tail -n 2500 "BlueSteel-tvOS-test.log"
  - test -f "BlueSteel-tvOS-test.log" && LINE_BEFORE=`cat "BlueSteel-tvOS-test.log" | grep -n "IDETestOperationsObserverDebug. Writing diagnostic log for test session to." | awk -F':' '{print $1}'` && LINE=`expr $LINE_BEFORE + 1` && LOG_FILE=`head -n $LINE "BlueSteel-tvOS-test.log" | tail -n 1` && cat "$LOG_FILE"
  - test -f "BlueSteel-watchOS-build.log" && tail -n 2500 "BlueSteel-watchOS-build.log"

