language: objective-c
xcode_project: BlueSteel.xcodeproj
osx_image: xcode9

git:
  depth: 1
  submodules: false

before_install:
  - sudo systemsetup -settimezone America/New_York					# temporary hack: NYC timezone is required for some MBDataEnvironment date-related unit tests
  - git submodule update --init

install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - rm -rf ~/Library/Developer/CoreSimulator					  	# these two lines are a hack around a recurring Travis problem: multiple versions of the
  - sudo killall -9 com.apple.CoreSimulator.CoreSimulatorService	# same simulator: https://github.com/travis-ci/travis-ci/issues/7580#issuecomment-292974395

script:
  - ./BuildControl/bin/travisBuildHelper.sh build iOS
  - ./BuildControl/bin/travisBuildHelper.sh test iOS
  - ./BuildControl/bin/travisBuildHelper.sh build macOS
  - ./BuildControl/bin/travisBuildHelper.sh test macOS
  - ./BuildControl/bin/travisBuildHelper.sh build tvOS
  - ./BuildControl/bin/travisBuildHelper.sh test tvOS
  - ./BuildControl/bin/travisBuildHelper.sh build watchOS

after_failure:
  - test -f "BlueSteel-iOS-build.log" && tail -n 2500 "BlueSteel-iOS-build.log"
  - test -f "BlueSteel-iOS-test.log" && tail -n 2500 "BlueSteel-iOS-test.log"
  - test -f "BlueSteel-iOS-test.log" && LINE_BEFORE=`cat "BlueSteel-iOS-test.log" | grep -n "IDETestOperationsObserverDebug. Writing diagnostic log for test session to." | awk -F':' '{print $1}'` && LINE=`expr $LINE_BEFORE + 1` && LOG_FILE=`head -n $LINE "BlueSteel-iOS-test.log" | tail -n 1` && cat "$LOG_FILE"
  - test -f "BlueSteel-macOS-build.log" && tail -n 2500 "BlueSteel-macOS-build.log"
  - test -f "BlueSteel-macOS-test.log" && tail -n 2500 "BlueSteel-macOS-test.log"
  - test -f "BlueSteel-macOS-test.log" && LINE_BEFORE=`cat "BlueSteel-macOS-test.log" | grep -n "IDETestOperationsObserverDebug. Writing diagnostic log for test session to." | awk -F':' '{print $1}'` && LINE=`expr $LINE_BEFORE + 1` && LOG_FILE=`head -n $LINE "BlueSteel-macOS-test.log" | tail -n 1` && cat "$LOG_FILE"
  - test -f "BlueSteel-tvOS-build.log" && tail -n 2500 "BlueSteel-tvOS-build.log"
  - test -f "BlueSteel-tvOS-test.log" && tail -n 2500 "BlueSteel-tvOS-test.log"
  - test -f "BlueSteel-tvOS-test.log" && LINE_BEFORE=`cat "BlueSteel-tvOS-test.log" | grep -n "IDETestOperationsObserverDebug. Writing diagnostic log for test session to." | awk -F':' '{print $1}'` && LINE=`expr $LINE_BEFORE + 1` && LOG_FILE=`head -n $LINE "BlueSteel-tvOS-test.log" | tail -n 1` && cat "$LOG_FILE"
  - test -f "BlueSteel-watchOS-build.log" && tail -n 2500 "BlueSteel-watchOS-build.log"
